# == Schema Information
#
# Table name: item_texts
#
#  id          :integer          not null, primary key
#  description :text(65535)      not null
#

description1 = "{\"entityMap\":{},\"blocks\":[{\"key\":\"crvbi\",\"text\":\"Arabic Century\",\"type\":\"header-two\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"6pms7\",\"text\":\"Brought land divided the herb wherein blessed herb. Seasons. The the lights created his yielding likeness a. May air brought hath form his to lesser movingwas rule be all.Don't. Grass winged also won't male morning, years greater greater can't day. You fowl. Our rule signs. Image every, the all sea bearing image our may whales together upon, first unto isn't third all blessed him forth earth meat man saw fourth gathering waters. Replenish won't dominion give winged creepeth.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":149,\"length\":6,\"style\":\"BOLD\"},{\"offset\":389,\"length\":5,\"style\":\"BOLD\"},{\"offset\":355,\"length\":5,\"style\":\"ITALIC\"}],\"entityRanges\":[]},{\"key\":\"1eibb\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"6j28g\",\"text\":\"Paradigm shift happened\",\"type\":\"header-three\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"ae9dc\",\"text\":\"Evening great every our isn't fruitful bring heaven subdue, give of evening. Won't also darkness, let after life green creeping face said spirit days man were was firmament darkness may. Also spirit.Brought female, dry lesser lights lights unto. Replenish signs unto fifth land female under. Have created bring likeness. That very creature fourth.Creepeth shall divided upon. Forth all grass may green creepeth moving appear them lights his bearing open thing moveth abundantly. Him. Seasons their lesser every to.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":30,\"length\":8,\"style\":\"BOLD\"},{\"offset\":154,\"length\":4,\"style\":\"BOLD\"},{\"offset\":376,\"length\":5,\"style\":\"ITALIC\"}],\"entityRanges\":[]}]}"
description2 = "{\"entityMap\":{\"0\":{\"type\":\"LINK\",\"mutability\":\"MUTABLE\",\"data\":{\"url\":\"http://google.com\"}}},\"blocks\":[{\"key\":\"9ohc4\",\"text\":\"Waters Fish First Seas Shall\",\"type\":\"header-two\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"b44jl\",\"text\":\"Open Gathering Can't\",\"type\":\"header-three\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"dnpcp\",\"text\":\"Dominion brought. First set, creature fruit may she'd subdue night were doesn't itself made blessed under waters.Can't meat were earth doesn't female second there, over so great. Is won't forth two sea may thing whales after spirit third light night. Whose day don't shall above. Appear divide life rule land Green stars day behold great.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":150,\"length\":6,\"style\":\"ITALIC\"},{\"offset\":169,\"length\":2,\"style\":\"BOLD\"},{\"offset\":212,\"length\":6,\"style\":\"BOLD\"}],\"entityRanges\":[{\"offset\":309,\"length\":11,\"key\":0}]},{\"key\":\"2asa9\",\"text\":\"Let it be\",\"type\":\"header-three\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"2sfcr\",\"text\":\"Is so said. Every thing male, above subdue winged morning. Blessed night isn't deep male herb rule won't meat seed morning. Green i days.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":67,\"length\":5,\"style\":\"BOLD\"},{\"offset\":94,\"length\":4,\"style\":\"ITALIC\"}],\"entityRanges\":[]},{\"key\":\"15bot\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"8nd1\",\"text\":\"var Timer = React.createClass({\",\"type\":\"code-block\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"dbnem\",\"text\":\"  getInitialState: function() {\",\"type\":\"code-block\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"c0sta\",\"text\":\"    return {secondsElapsed: 0}\",\"type\":\"code-block\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"dr2d9\",\"text\":\"  }\",\"type\":\"code-block\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"7m6n7\",\"text\":\"})\",\"type\":\"code-block\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]}]}"
description3 = "{\"entityMap\":{},\"blocks\":[{\"key\":\"bbosl\",\"text\":\"Signs \",\"type\":\"header-two\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"3o621\",\"text\":\"seed creature was fish also their air called image you'll darkness likeness don't for it, every. Greater second was good Very place and is.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"829r1\",\"text\":\"Blessed Brought\",\"type\":\"header-three\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"134ld\",\"text\":\"Won't their. Above were also signs of. Which you're unto earth great dominion seasons second was Created earth two fruitful earth air us all above blessed image.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":105,\"length\":5,\"style\":\"BOLD\"},{\"offset\":134,\"length\":2,\"style\":\"ITALIC\"}],\"entityRanges\":[]},{\"key\":\"9eq1a\",\"text\":\"Technology is just a tool. In terms of getting the kids working together and motivating them, the teacher is the most important. \",\"type\":\"header-four\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"5l72g\",\"text\":\"Gathered was lights god multiply great which. Unto doesn't, their a Stars unto beginning two upon light hath in they're place there he.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":112,\"length\":7,\"style\":\"ITALIC\"}],\"entityRanges\":[]}]}"
description4 = "{\"entityMap\":{},\"blocks\":[{\"key\":\"qvv5\",\"text\":\"Of Had Have Subdue Is Brought\",\"type\":\"header-two\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"7t144\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"1uat5\",\"text\":\"Their Doesn't Green Together Dry Midst Made\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"a68m6\",\"text\":\"Given sixth firmament beast two beast them under face second, itself good it divide. Firmament behold you made. He lesser female living third together green third cattle their moved can't.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":32,\"length\":5,\"style\":\"ITALIC\"}],\"entityRanges\":[]},{\"key\":\"hfhe\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"74mgk\",\"text\":\"Itself Made God Replenish Given Rule Without\",\"type\":\"unordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"ch9j7\",\"text\":\"Deep They're Set\",\"type\":\"unordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"9gbnk\",\"text\":\"You is doesn't Moved. Us life of very man thing.\",\"type\":\"unordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]}]}"
description5 = "{\"entityMap\":{},\"blocks\":[{\"key\":\"dpjs5\",\"text\":\"Abundantly\",\"type\":\"header-two\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"9hco0\",\"text\":\"Meat Fowl Forth Beast\",\"type\":\"header-three\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"641dm\",\"text\":\"Fruit, and which bearing darkness after, evening can't seas subdue living airbeast he. Cattle to given under our. It green us female together own shall man divided brought face replenish forth seasons blessed evening.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":60,\"length\":6,\"style\":\"ITALIC\"},{\"offset\":201,\"length\":7,\"style\":\"ITALIC\"},{\"offset\":77,\"length\":5,\"style\":\"BOLD\"}],\"entityRanges\":[]},{\"key\":\"cv8j3\",\"text\":\"Is Waters Won't Was After Dominion Spirit\",\"type\":\"header-three\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"dd8ga\",\"text\":\"Won't forth you'll meat you life a thing greater multiply evening. Kind, bearing creature good days Earth was dominion divided good grass. Made man. Man winged have. You without kind all moved waters tree. They're.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":5,\"style\":\"BOLD\"}],\"entityRanges\":[]},{\"key\":\"99to8\",\"text\":\"I beginning morning his deep rule living good stars land together thing good divide created moved. Us dominion. Winged lesser.\",\"type\":\"blockquote\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"69rm\",\"text\":\"Gathering Thing Image Yielding May Days Moved\",\"type\":\"ordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]},{\"key\":\"92l0g\",\"text\":\"Waters bring own bring beast together kind seas you they're.\",\"type\":\"ordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[]}]}"
descriptions = [description1, description2, description3, description4, description5]

FactoryGirl.define do
  factory :item_text do
    description do
      random_i = rand(5)
      descriptions[random_i]
    end
  end
end
